version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=filmflam
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 25

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres  # This is the name of the postgres service above
      - DB_PORT=5432
      - DB_NAME=filmflam
      - DB_USER=user
      - DB_PASS=pass
      - PORT=8080
      - HOST=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "80:80"
    environment:
      - API_HOST=backend
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db:
    driver: local